language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
after_success:
- npm run travis-deploy-once "npm run semantic-release"
script:
- npm run build
- npm run lint
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  ssh_known_hosts: dev.wir.by
before_deploy:
- openssl aes-256-cbc -K $encrypted_0edcbc894897_key -iv $encrypted_0edcbc894897_iv
  -in deploy_travis_markup_rsa.enc -out /tmp/deploy_travis_markup_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_travis_markup_rsa
- ssh-add /tmp/deploy_travis_markup_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist wir-dev@dev.wir.by:/home/wir-dev/experiment/
  on:
    branch: deploy
